### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by joshchngs** [gongzhang/swift-complex-number#1]
Hey,

I'd like to use your project, but right now it's missing a license - would you mind adding one?

Cheers,
Josh

**Comment by gongzhang** [comment]
Done. 😎

**Comment by joshchngs** [comment]
Damn you're quick

**Comment by gongzhang** [comment]
![bender-applause_medium](https://user-images.githubusercontent.com/4470629/29209702-790f723a-7ec2-11e7-901b-230e1206bb3d.gif)
